/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FacultyOfLawStudentResultSystem;

import java.awt.Component;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.MessageFormat;

import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableColumn;

/**
 *
 * @author Администратор
 */
public class FacultyOfLawStudentResultSystem extends javax.swing.JFrame {

    /**
     * Creates new form FacultyOfLawStudentResultSystem
     */
    public FacultyOfLawStudentResultSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jbtnPrint = new javax.swing.JButton();
        jbtnAdd = new javax.swing.JButton();
        jbtnResult = new javax.swing.JButton();
        jbtnTranscript = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jtxtDate = new javax.swing.JTextField();
        jtxtRanking = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        jtxtTotalScore3 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtTranscript = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcboGender = new javax.swing.JComboBox<>();
        jtxtTotalScore1 = new javax.swing.JTextField();
        jtxtTotalScore2 = new javax.swing.JTextField();
        jtxtTotalScore = new javax.swing.JTextField();
        jtxtTotalScore4 = new javax.swing.JTextField();
        jtxtTotalScore5 = new javax.swing.JTextField();
        jtxtTotalScore7 = new javax.swing.JTextField();
        jtxtTotalScore6 = new javax.swing.JTextField();
        jtxtTotalScore8 = new javax.swing.JTextField();
        jtxtTotalScore9 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jcboCourse = new javax.swing.JComboBox<>();
        jtxtTotalScore10 = new javax.swing.JTextField();
        jtxtTotalScore11 = new javax.swing.JTextField();
        jtxtTotalScore12 = new javax.swing.JTextField();
        jtxtTotalScore13 = new javax.swing.JTextField();
        jtxtTotalScore14 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 194, 203), 8));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1400, 750));

        jPanel1.setPreferredSize(new java.awt.Dimension(1340, 660));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 194, 203), 8));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnPrint.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnPrint.setText("Печать");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 100, 40));

        jbtnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnAdd.setText("Добавить");
        jPanel3.add(jbtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 40));

        jbtnResult.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnResult.setText("Результат");
        jbtnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResultActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 120, 40));

        jbtnTranscript.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnTranscript.setText("Расшифровка");
        jbtnTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTranscriptActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnTranscript, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 130, 40));

        jbtnReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnReset.setText("Сброс");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 90, 40));

        jbtnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnExit.setText("Выход");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 90, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, 880, 80));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 194, 203), 8));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("8");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 30, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("7");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 30, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("6");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 30, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("5");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 30, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("4");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 30, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("3");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 30, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("2");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 30, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("1");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 30, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel26.setText("№");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel27.setText("Выбор курса");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel28.setText("Счёт");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setText("Дата");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setText("Рейтинг");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 80, 30));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setText("Всего баллов");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 130, 30));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("0");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 70, 30));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("0");
        jPanel5.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 70, 30));

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("0");
        jPanel5.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 70, 30));

        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("0");
        jPanel5.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 70, 30));

        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("0");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 70, 30));

        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("0");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 70, 30));

        jTextField10.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("0");
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 70, 30));

        jTextField11.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("0");
        jPanel5.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 70, 30));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 194, 203), 8));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel32.setText("jLabel1");
        jPanel8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel33.setText("jLabel1");
        jPanel8.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel34.setText("jLabel1");
        jPanel8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel35.setText("jLabel1");
        jPanel8.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel36.setText("jLabel1");
        jPanel8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel37.setText("jLabel1");
        jPanel8.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel38.setText("jLabel1");
        jPanel8.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel39.setText("jLabel1");
        jPanel8.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel40.setText("jLabel1");
        jPanel8.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel41.setText("jLabel1");
        jPanel8.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel42.setText("jLabel1");
        jPanel8.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel43.setText("jLabel1");
        jPanel8.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel44.setText("jLabel1");
        jPanel8.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel45.setText("jLabel1");
        jPanel8.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jTextField12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField12.setText("jTextField1");
        jPanel8.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 130, 30));

        jTextField13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField13.setText("jTextField1");
        jPanel8.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 130, 30));

        jTextField14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField14.setText("jTextField1");
        jPanel8.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 130, 30));

        jTextField15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField15.setText("jTextField1");
        jPanel8.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 130, 30));

        jTextField16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField16.setText("jTextField1");
        jPanel8.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 130, 30));

        jTextField17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField17.setText("jTextField1");
        jPanel8.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 130, 30));

        jTextField18.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField18.setText("jTextField1");
        jPanel8.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 130, 30));

        jTextField19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField19.setText("jTextField1");
        jPanel8.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 130, 30));

        jTextField20.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField20.setText("jTextField1");
        jPanel8.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 130, 30));

        jTextField21.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField21.setText("jTextField1");
        jPanel8.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 130, 30));

        jTextField22.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField22.setText("jTextField1");
        jPanel8.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 130, 30));

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 400, 500));

        jtxtDate.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDateActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 240, 30));

        jtxtRanking.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtRanking.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(jtxtRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 240, 30));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Основы проектной деятельности", "Саморазвитие и инклюзивная подготовка персонала", "Правовое обеспечение национальной безопасности", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 250, 30));

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Административное право", "Гражданское право", "Иностранный язык в сфере юриспруденции", " ", " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 250, 30));

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Основы информационной безопасности", "Правовые основы социального государства", "Трудовое право", " " }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 250, 30));

        jComboBox4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Политическая система общества", "Уголовное право", "Основы управления проектами", " " }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 250, 30));

        jComboBox5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Физическая культура и спорт", "Конституционное право", "Административное право", " " }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 250, 30));

        jComboBox6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Гражданское право", "Муниципальное право", "Правовые основы антикоррупционного поведения", " " }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 250, 30));

        jComboBox7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 190, 30));

        jComboBox8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Иностранный язык", "Философия", "Удмуртский язык в межкультурной коммуникации", " " }));
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 250, 30));

        jComboBox10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Конституционное право", "Административное право", "Саморазвитие и инклюзивная подготовка персонала" }));
        jComboBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox10ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 250, 30));

        jtxtTotalScore3.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtTotalScore3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(jtxtTotalScore3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 240, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 400, 540));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 194, 203), 8));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtTranscript.setColumns(20);
        jtxtTranscript.setRows(5);
        jScrollPane1.setViewportView(jtxtTranscript);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 470, 520));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel23.setText("jLabel1");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setText("jLabel1");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel25.setText("jLabel1");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 490, 540));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 194, 203), 8));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Имя");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("ИД Студента");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Отчество");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Фамилия");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Д.Р.");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Пол");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Телефон");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("E-mail");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jcboGender.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jcboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Мужской", "Женский" }));
        jcboGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboGenderActionPerformed(evt);
            }
        });
        jPanel7.add(jcboGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 240, 30));

        jtxtTotalScore1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtTotalScore1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jtxtTotalScore1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 240, 30));

        jtxtTotalScore2.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtTotalScore2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jtxtTotalScore2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 240, 30));

        jtxtTotalScore.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtTotalScore.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jtxtTotalScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 240, 30));

        jtxtTotalScore4.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtTotalScore4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jtxtTotalScore4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 190, 30));

        jtxtTotalScore5.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtTotalScore5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jtxtTotalScore5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 240, 30));

        jtxtTotalScore7.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtTotalScore7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jtxtTotalScore7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 240, 30));

        jtxtTotalScore6.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtTotalScore6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jtxtTotalScore6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 240, 30));

        jtxtTotalScore8.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtTotalScore8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jtxtTotalScore8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 240, 30));

        jtxtTotalScore9.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtTotalScore9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jtxtTotalScore9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 240, 30));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 410, 350));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 194, 203), 8));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Специальность");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Код курса");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Институт");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Декан Института");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Руководитель программы");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Преподаватель курса");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jcboCourse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jcboCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Выберите предмет", "Юриспруденция", "Правовое обеспечение национальной безопасности", "Правоохранительная деятельность", "Информационная безопасность" }));
        jcboCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboCourseActionPerformed(evt);
            }
        });
        jPanel4.add(jcboCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 220, 30));

        jtxtTotalScore10.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtTotalScore10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(jtxtTotalScore10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 220, 30));

        jtxtTotalScore11.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtTotalScore11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(jtxtTotalScore11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 220, 30));

        jtxtTotalScore12.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtTotalScore12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTotalScore12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalScore12ActionPerformed(evt);
            }
        });
        jPanel4.add(jtxtTotalScore12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 220, 30));

        jtxtTotalScore13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtTotalScore13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTotalScore13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalScore13ActionPerformed(evt);
            }
        });
        jPanel4.add(jtxtTotalScore13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 220, 30));

        jtxtTotalScore14.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtTotalScore14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(jtxtTotalScore14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 220, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 410, 270));

        jLabel46.setText("Created by Iulia Tikhonova");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 640, -1, -1));

        jTabbedPane1.addTab("Записи университета", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 194, 203), 8));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ИД Студента", "Имя", "Фамилия", "Отчество", "Пол", "Дата рождения", "Телефон", "E-mail", "Специальность", "Код специальности", "Module1", "Module2", "Module3", "Module4", "Module5", "Module6", "Module7", "Module8", "Score1", "Score2", "Score3", "Score4", "Score5", "Score6", "Score7", "Score8", "TotalScore", "Рейтинг", "Дата"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jTable1);

        jPanel9.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1260, 490));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 1300, 510));

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 194, 203), 8));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel47.setText("Система учета рейтинга студентов");
        jPanel10.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1300, 100));

        jTabbedPane1.addTab("Записи студента", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1350, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTranscriptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnTranscriptActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox10ActionPerformed

    private void jtxtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDateActionPerformed

    private void jcboGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboGenderActionPerformed

    private void jcboCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboCourseActionPerformed

    private void jtxtTotalScore12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalScore12ActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalScore12ActionPerformed

    private void jtxtTotalScore13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalScore13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalScore13ActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        // TODO add your handling code here:
        try {
            jtxtTranscript.print();
        }
        catch(java.awt.print.PrinterException e) 
        {
            System.err.format("Принтер не найден", e.getMessage());
        }
            
  
    }//GEN-LAST:event_jbtnPrintActionPerformed
    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        // TODO add your handling code here:
        
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Вы хотите закрыть программу?", "Система учета рейтинга студентов",
                JOptionPane.YES_NO_OPTION  ) == JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnResultActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
         // TODO add your handling code here:
         JTextField jtxt = null;
         JComboBox jcbo = null; 
         
         
         
         for (Component c:jPanel7.getComponents()) 
         {
             if (c.getClass().toString().contains("javax.swing.JTextField")) 
             {
                 jtxt = (JTextField)c;
                 jtxt.setText(null);
             }
         }
         
         for (Component c:jPanel5.getComponents()) 
         {
             if (c.getClass().toString().contains("javax.swing.JComboBox")) 
             {
                 jcbo = (JComboBox)c;
                 jcbo.setSelectedIndex(0);
             }
         }
         for (Component c:jPanel5.getComponents()) 
         {
             if (c.getClass().toString().contains("javax.swing.JTextField")) 
             {
                 jtxt = (JTextField)c;
                 jtxt.setText(null);
             }
         }
         
         for (Component c:jPanel4.getComponents()) 
         {
             if (c.getClass().toString().contains("javax.swing.JTextField")) 
             {
                 jtxt = (JTextField)c;
                 jtxt.setText(null);
             }
         }
         // Сделаем раздельно для выбора пола, расшифровки и специальности
    jtxtTranscript.setText(null);
    jcboGender.setSelectedIndex(0);
    jcboCourse.setSelectedIndex(0);     
         

         
      
         
    }//GEN-LAST:event_jbtnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacultyOfLawStudentResultSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacultyOfLawStudentResultSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacultyOfLawStudentResultSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacultyOfLawStudentResultSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacultyOfLawStudentResultSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnResult;
    private javax.swing.JButton jbtnTranscript;
    private javax.swing.JComboBox<String> jcboCourse;
    private javax.swing.JComboBox<String> jcboGender;
    private javax.swing.JTextField jtxtDate;
    private javax.swing.JTextField jtxtRanking;
    private javax.swing.JTextField jtxtTotalScore;
    private javax.swing.JTextField jtxtTotalScore1;
    private javax.swing.JTextField jtxtTotalScore10;
    private javax.swing.JTextField jtxtTotalScore11;
    private javax.swing.JTextField jtxtTotalScore12;
    private javax.swing.JTextField jtxtTotalScore13;
    private javax.swing.JTextField jtxtTotalScore14;
    private javax.swing.JTextField jtxtTotalScore2;
    private javax.swing.JTextField jtxtTotalScore3;
    private javax.swing.JTextField jtxtTotalScore4;
    private javax.swing.JTextField jtxtTotalScore5;
    private javax.swing.JTextField jtxtTotalScore6;
    private javax.swing.JTextField jtxtTotalScore7;
    private javax.swing.JTextField jtxtTotalScore8;
    private javax.swing.JTextField jtxtTotalScore9;
    private javax.swing.JTextArea jtxtTranscript;
    // End of variables declaration//GEN-END:variables
}
