/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FacultyOfLawStudentResultSystem;

import java.awt.Component;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.netbeans.lib.awtextra.*;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.MessageFormat;

import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableColumn;
import java.util.logging.Logger;

import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author Администратор
 */
public class FacultyOfLawStudentResultSystem extends javax.swing.JFrame {

    String username = "root";
    String password = "123456";
    String dataCon = "jdbc:mysql://localhost:3306/resultdb";
    
    Connection sqlCon = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    int q, i; 
    
    public FacultyOfLawStudentResultSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void uploadDB() {
        
        try 
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlCon = DriverManager.getConnection(dataCon, username, password);
            if (sqlCon != null) {
                System.out.println("Connected to the database test1");
            }
            pst = sqlCon.prepareStatement("select * from resultdb");
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
             // that is for my table 
            DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
            RecordTable.setRowCount(0);
            
            while (rs.next()) 
            {
                Vector columnData = new Vector();
                
                for (i = 1; i <= q; i++) {
                    
                    columnData.add(rs.getLong("StudentID"));
                    columnData.add(rs.getString("Firstname"));
                    columnData.add(rs.getString("Surname"));
                    columnData.add(rs.getString("Otchestvo"));
                    columnData.add(rs.getString("Gender"));
                    columnData.add(rs.getString("DOB"));
                    columnData.add(rs.getString("Mobile"));
                    columnData.add(rs.getString("Email"));
                    
                    columnData.add(rs.getString("Course"));
                    columnData.add(rs.getString("CourseCode"));
                    
                    columnData.add(rs.getString("Module1"));
                    columnData.add(rs.getString("Module2"));
                    columnData.add(rs.getString("Module3"));
                    columnData.add(rs.getString("Module4"));
                    columnData.add(rs.getString("Module5"));
                    columnData.add(rs.getString("Module6"));
                    columnData.add(rs.getString("Module7"));
                    columnData.add(rs.getString("Module8"));
                    
                    columnData.add(rs.getInt("Score1"));
                    columnData.add(rs.getInt("Score2"));
                    columnData.add(rs.getInt("Score3"));
                    columnData.add(rs.getInt("Score4"));
                    columnData.add(rs.getInt("Score5"));
                    columnData.add(rs.getInt("Score6"));
                    columnData.add(rs.getInt("Score7"));
                    columnData.add(rs.getInt("Score8"));
                    
                    columnData.add(rs.getInt("TotalScore"));
                    columnData.add(rs.getString("Ranking"));
                    columnData.add(rs.getString("Date"));
                    
                }
                RecordTable.addRow(columnData);
  
            }
        }
        catch(Exception ex)  
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jbtnPrint = new javax.swing.JButton();
        jbtnAdd = new javax.swing.JButton();
        jbtnResult = new javax.swing.JButton();
        jbtnTranscript = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jtxtScore1 = new javax.swing.JTextField();
        jtxtScore2 = new javax.swing.JTextField();
        jtxtScore3 = new javax.swing.JTextField();
        jtxtScore6 = new javax.swing.JTextField();
        jtxtScore5 = new javax.swing.JTextField();
        jtxtScore4 = new javax.swing.JTextField();
        jtxtScore8 = new javax.swing.JTextField();
        jtxtScore7 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jtxtDate = new javax.swing.JTextField();
        jtxtTotalScore = new javax.swing.JTextField();
        jcboModule3 = new javax.swing.JComboBox<>();
        jcboModule1 = new javax.swing.JComboBox<>();
        jcboModule2 = new javax.swing.JComboBox<>();
        jcboModule6 = new javax.swing.JComboBox<>();
        jcboModule5 = new javax.swing.JComboBox<>();
        jcboModule4 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jcboModule7 = new javax.swing.JComboBox<>();
        jcboModule8 = new javax.swing.JComboBox<>();
        jtxtRanking = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtTranscript = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcboGender = new javax.swing.JComboBox<>();
        jtxtTotalScore1 = new javax.swing.JTextField();
        jtxtTotalScore2 = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jtxtStudentID = new javax.swing.JTextField();
        jtxtSurname = new javax.swing.JTextField();
        jtxtFirstname = new javax.swing.JTextField();
        jtxtOtchestvo = new javax.swing.JTextField();
        jtxtDOB = new javax.swing.JTextField();
        jtxtMobile = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jcboCourse = new javax.swing.JComboBox<>();
        jtxtCourseCode = new javax.swing.JTextField();
        jtxtFaculty = new javax.swing.JTextField();
        jtxtDekan = new javax.swing.JTextField();
        jtxtCourseTeacher = new javax.swing.JTextField();
        jtxtStarosta = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 194, 203), 8));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1400, 750));

        jPanel1.setPreferredSize(new java.awt.Dimension(1340, 660));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 194, 203), 8));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnPrint.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnPrint.setText("Печать");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 100, 40));

        jbtnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnAdd.setText("Добавить");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 40));

        jbtnResult.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnResult.setText("Результат");
        jbtnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResultActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 120, 40));

        jbtnTranscript.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnTranscript.setText("Расшифровка");
        jbtnTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTranscriptActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnTranscript, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 130, 40));

        jbtnReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnReset.setText("Сброс");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 90, 40));

        jbtnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnExit.setText("Выход");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 90, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, 880, 80));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 194, 203), 8));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("8");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 30, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("7");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 30, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("6");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 30, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("5");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 30, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("4");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 30, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("3");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 30, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("2");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 30, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("1");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 30, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel26.setText("№");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel27.setText("Выбор курса");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel28.setText("Счёт");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setText("Дата");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setText("Рейтинг");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 80, 30));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setText("Всего баллов");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 130, 30));

        jtxtScore1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtScore1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtScore1.setText("0");
        jtxtScore1.setEnabled(false);
        jtxtScore1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtScore1ActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtScore1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 70, 30));

        jtxtScore2.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtScore2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtScore2.setText("0");
        jtxtScore2.setEnabled(false);
        jPanel5.add(jtxtScore2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 70, 30));

        jtxtScore3.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtScore3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtScore3.setText("0");
        jtxtScore3.setEnabled(false);
        jPanel5.add(jtxtScore3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 70, 30));

        jtxtScore6.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtScore6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtScore6.setText("0");
        jtxtScore6.setEnabled(false);
        jPanel5.add(jtxtScore6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 70, 30));

        jtxtScore5.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtScore5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtScore5.setText("0");
        jtxtScore5.setEnabled(false);
        jtxtScore5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtScore5ActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtScore5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 70, 30));

        jtxtScore4.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtScore4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtScore4.setText("0");
        jtxtScore4.setEnabled(false);
        jtxtScore4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtScore4ActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtScore4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 70, 30));

        jtxtScore8.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtScore8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtScore8.setText("0");
        jtxtScore8.setEnabled(false);
        jtxtScore8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtScore8ActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtScore8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 70, 30));

        jtxtScore7.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtScore7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtScore7.setText("0");
        jtxtScore7.setEnabled(false);
        jPanel5.add(jtxtScore7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 70, 30));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 194, 203), 8));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel32.setText("jLabel1");
        jPanel8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel33.setText("jLabel1");
        jPanel8.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel34.setText("jLabel1");
        jPanel8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel35.setText("jLabel1");
        jPanel8.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel36.setText("jLabel1");
        jPanel8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel37.setText("jLabel1");
        jPanel8.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel38.setText("jLabel1");
        jPanel8.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel39.setText("jLabel1");
        jPanel8.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel40.setText("jLabel1");
        jPanel8.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel41.setText("jLabel1");
        jPanel8.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel42.setText("jLabel1");
        jPanel8.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel43.setText("jLabel1");
        jPanel8.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel44.setText("jLabel1");
        jPanel8.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel45.setText("jLabel1");
        jPanel8.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jTextField12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField12.setText("jTextField1");
        jPanel8.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 130, 30));

        jTextField13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField13.setText("jTextField1");
        jPanel8.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 130, 30));

        jTextField14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField14.setText("jTextField1");
        jPanel8.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 130, 30));

        jTextField15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField15.setText("jTextField1");
        jPanel8.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 130, 30));

        jTextField16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField16.setText("jTextField1");
        jPanel8.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 130, 30));

        jTextField17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField17.setText("jTextField1");
        jPanel8.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 130, 30));

        jTextField18.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField18.setText("jTextField1");
        jPanel8.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 130, 30));

        jTextField19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField19.setText("jTextField1");
        jPanel8.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 130, 30));

        jTextField20.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField20.setText("jTextField1");
        jPanel8.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 130, 30));

        jTextField21.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField21.setText("jTextField1");
        jPanel8.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 130, 30));

        jTextField22.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField22.setText("jTextField1");
        jPanel8.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 130, 30));

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 400, 500));

        jtxtDate.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDateActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 240, 30));

        jtxtTotalScore.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtTotalScore.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(jtxtTotalScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 240, 30));

        jcboModule3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jcboModule3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Административное право", "Административное право", "Административное право", " " }));
        jcboModule3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule3ActionPerformed(evt);
            }
        });
        jPanel5.add(jcboModule3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 250, 30));

        jcboModule1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jcboModule1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Административное право", "Административное право", "Административное право", " ", " " }));
        jcboModule1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule1ActionPerformed(evt);
            }
        });
        jPanel5.add(jcboModule1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 250, 30));

        jcboModule2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jcboModule2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Административное право", "Административное право", "Административное право", " " }));
        jcboModule2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule2ActionPerformed(evt);
            }
        });
        jPanel5.add(jcboModule2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 250, 30));

        jcboModule6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jcboModule6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Административное право", "Административное право", "Административное право", " " }));
        jcboModule6.setToolTipText("");
        jcboModule6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule6ActionPerformed(evt);
            }
        });
        jPanel5.add(jcboModule6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 250, 30));

        jcboModule5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jcboModule5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Административное право", "Административное право", "Административное право", " " }));
        jcboModule5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule5ActionPerformed(evt);
            }
        });
        jPanel5.add(jcboModule5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 250, 30));

        jcboModule4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jcboModule4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Административное право", "Административное право", "Административное право", " " }));
        jcboModule4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule4ActionPerformed(evt);
            }
        });
        jPanel5.add(jcboModule4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 250, 30));

        jComboBox7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 190, 30));

        jcboModule7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jcboModule7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Административное право", "Административное право", "Административное право", " " }));
        jcboModule7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule7ActionPerformed(evt);
            }
        });
        jPanel5.add(jcboModule7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 250, 30));

        jcboModule8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jcboModule8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Административное право", "Административное право", "Административное право", " " }));
        jcboModule8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule8ActionPerformed(evt);
            }
        });
        jPanel5.add(jcboModule8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 250, 30));

        jtxtRanking.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtRanking.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(jtxtRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 240, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 400, 540));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 194, 203), 8));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtTranscript.setColumns(20);
        jtxtTranscript.setRows(5);
        jScrollPane1.setViewportView(jtxtTranscript);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 470, 520));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 490, 540));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 194, 203), 8));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Имя");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("ИД Студента");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Отчество");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Фамилия");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Д.Р.");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Пол");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Телефон");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("E-mail");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jcboGender.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jcboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Мужской", "Женский" }));
        jcboGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboGenderActionPerformed(evt);
            }
        });
        jPanel7.add(jcboGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 240, 30));

        jtxtTotalScore1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtTotalScore1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jtxtTotalScore1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 240, 30));

        jtxtTotalScore2.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtTotalScore2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jtxtTotalScore2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 240, 30));

        jtxtEmail.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jtxtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 240, 30));

        jtxtStudentID.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtStudentID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jtxtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 190, 30));

        jtxtSurname.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtSurname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jtxtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 240, 30));

        jtxtFirstname.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtFirstname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jtxtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 240, 30));

        jtxtOtchestvo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jtxtOtchestvo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jtxtOtchestvo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 240, 30));

        jtxtDOB.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtDOB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jtxtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 240, 30));

        jtxtMobile.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtMobile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jtxtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 240, 30));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 410, 350));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 194, 203), 8));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Специальность");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Код курса");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Институт");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Декан Института");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Староста");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 60, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Преподаватель курса");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jcboCourse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jcboCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Выберите предмет", "Юриспруденция", "Правовое обеспечение национальной безопасности", "Правоохранительная деятельность", "Информационная безопасность" }));
        jcboCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboCourseActionPerformed(evt);
            }
        });
        jPanel4.add(jcboCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 220, 30));

        jtxtCourseCode.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtCourseCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(jtxtCourseCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 220, 30));

        jtxtFaculty.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtFaculty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(jtxtFaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 220, 30));

        jtxtDekan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtxtDekan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtDekan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDekanActionPerformed(evt);
            }
        });
        jPanel4.add(jtxtDekan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 220, 30));

        jtxtCourseTeacher.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtCourseTeacher.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCourseTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCourseTeacherActionPerformed(evt);
            }
        });
        jPanel4.add(jtxtCourseTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 220, 30));

        jtxtStarosta.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jtxtStarosta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(jtxtStarosta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 220, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 410, 270));

        jLabel46.setText("Created by Iulia Tikhonova");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 640, -1, -1));

        jTabbedPane1.addTab("Записи университета", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 194, 203), 8));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "StudentID", "Firstname", "Surname", "Otchestvo", "Gender", "DOB", "Mobile", "Email", "Course", "CourseCode", "Module1", "Module2", "Module3", "Module4", "Module5", "Module6", "Module7", "Module8", "Score1", "Score2", "Score3", "Score4", "Score5", "Score6", "Score7", "Score8", "TotalScore", "Ranking", "Date"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jTable1);

        jPanel9.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1280, 490));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 1300, 510));

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 194, 203), 8));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel47.setText("Система учета успеваемости студентов");
        jPanel10.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1300, 100));

        jTabbedPane1.addTab("Записи студента", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1350, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTranscriptActionPerformed
        // TODO add your handling code here:



        jtxtTranscript.append("\t\t Расшифровка \n"
        + "=====================================================\n"
        + "Номер регистрации студента:\t\t " + jtxtStudentID.getText() + "\n\n"
        + "Имя:     " + jtxtSurname.getText() + "\t     " + jtxtFirstname.getText() + "\t" + jtxtOtchestvo.getText() +  "\n\n"
        + "1: " + jcboModule1.getSelectedItem()+ "\t     " + jtxtScore1.getText() + "\n\n"
        + "2: " + jcboModule2.getSelectedItem()+ "\t     " + jtxtScore2.getText() + "\n\n"
        + "3: " + jcboModule3.getSelectedItem()+ "\t     " + jtxtScore3.getText() + "\n\n"
        + "4: " + jcboModule4.getSelectedItem()+ "\t     " + jtxtScore4.getText() + "\n\n"
        + "5: " + jcboModule5.getSelectedItem()+ "\t     " + jtxtScore5.getText() + "\n\n"
        + "6: " + jcboModule6.getSelectedItem()+ "\t     " + jtxtScore6.getText() + "\n\n"
        + "7: " + jcboModule7.getSelectedItem()+ "\t     " + jtxtScore7.getText() + "\n\n"
        + "8: " + jcboModule8.getSelectedItem()+ "\t     " + jtxtScore8.getText() + "\n\n"
        + "=====================================================\n"
        + "Всего баллов: \t\t"            + jtxtTotalScore.getText() + "\n"
        + "Рейтинг: \t\t"            + jtxtRanking.getText() + "\n"
        + "Дата: \t\t"            + jtxtDate.getText() + "\n"

        );

    }//GEN-LAST:event_jbtnTranscriptActionPerformed

    private void jtxtScore8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtScore8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtScore8ActionPerformed

    private void jtxtScore1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtScore1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtScore1ActionPerformed

    private void jtxtScore4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtScore4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtScore4ActionPerformed

    private void jtxtScore5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtScore5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtScore5ActionPerformed

    private void jcboModule3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule3ActionPerformed
        // TODO add your handling code here:
        if(jcboModule3.getSelectedItem().equals(""))
        {
            jtxtScore3.setText("0");
            jtxtScore3.setEnabled(false);
        }
        else
        {
            jtxtScore3.setText("0");
            jtxtScore3.setEnabled(true);
            jtxtScore3.requestFocus();
        }
    }//GEN-LAST:event_jcboModule3ActionPerformed

    private void jcboModule1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule1ActionPerformed
        // TODO add your handling code here:
        if(jcboModule1.getSelectedItem().equals(""))
        {
            jtxtScore1.setText("0");
            jtxtScore1.setEnabled(false);
        }
        else
        {
            jtxtScore1.setText("0");
            jtxtScore1.setEnabled(true);
            jtxtScore1.requestFocus();
        }

    }//GEN-LAST:event_jcboModule1ActionPerformed

    private void jcboModule2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule2ActionPerformed
        // TODO add your handling code here:
        if(jcboModule2.getSelectedItem().equals(""))
        {
            jtxtScore2.setText("0");
            jtxtScore2.setEnabled(false);
        }
        else
        {
            jtxtScore2.setText("0");
            jtxtScore2.setEnabled(true);
            jtxtScore2.requestFocus();
        }
    }//GEN-LAST:event_jcboModule2ActionPerformed

    private void jcboModule6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule6ActionPerformed
        // TODO add your handling code here:
        if(jcboModule6.getSelectedItem().equals(""))
        {
            jtxtScore6.setText("0");
            jtxtScore6.setEnabled(false);
        }
        else
        {
            jtxtScore6.setText("0");
            jtxtScore6.setEnabled(true);
            jtxtScore6.requestFocus();
        }
    }//GEN-LAST:event_jcboModule6ActionPerformed

    private void jcboModule5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule5ActionPerformed
        // TODO add your handling code here:
        if(jcboModule5.getSelectedItem().equals(""))
        {
            jtxtScore5.setText("0");
            jtxtScore5.setEnabled(false);
        }
        else
        {
            jtxtScore5.setText("0");
            jtxtScore5.setEnabled(true);
            jtxtScore5.requestFocus();
        }
    }//GEN-LAST:event_jcboModule5ActionPerformed

    private void jcboModule4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule4ActionPerformed
        // TODO add your handling code here:
        if(jcboModule4.getSelectedItem().equals(""))
        {
            jtxtScore4.setText("0");
            jtxtScore4.setEnabled(false);
        }
        else
        {
            jtxtScore4.setText("0");
            jtxtScore4.setEnabled(true);
            jtxtScore4.requestFocus();
        }
    }//GEN-LAST:event_jcboModule4ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jcboModule7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule7ActionPerformed
        // TODO add your handling code here:
        if(jcboModule7.getSelectedItem().equals(""))
        {
            jtxtScore7.setText("0");
            jtxtScore7.setEnabled(false);
        }
        else
        {
            jtxtScore7.setText("0");
            jtxtScore7.setEnabled(true);
            jtxtScore7.requestFocus();
        }
    }//GEN-LAST:event_jcboModule7ActionPerformed

    private void jcboModule8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule8ActionPerformed
        // TODO add your handling code here:
        if(jcboModule8.getSelectedItem().equals(""))
        {
            jtxtScore8.setText("0");
            jtxtScore8.setEnabled(false);
        }
        else
        {
            jtxtScore8.setText("0");
            jtxtScore8.setEnabled(true);
            jtxtScore8.requestFocus();
        }
    }//GEN-LAST:event_jcboModule8ActionPerformed

    private void jtxtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDateActionPerformed

    private void jcboGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboGenderActionPerformed

    private void jcboCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboCourseActionPerformed
        if (jcboCourse.getSelectedItem().equals("Юриспруденция"))
    {
        jtxtCourseCode.setText("LW0001");
        jtxtFaculty.setText("ИПСУБ");
        jtxtDekan.setText("к-т юр. наук Ившин В. Г");
        jtxtStarosta.setText("Иванов И. И.");
        jtxtCourseTeacher.setText("Сидоров С. С.");
        }
        else if (jcboCourse.getSelectedItem().equals("Правовое обеспечение национальной безопасности"))
    {
        jtxtCourseCode.setText("PNB0001");
        jtxtFaculty.setText("ИПСУБ");
        jtxtDekan.setText("к-т юр. наук Ившин В. Г");
        jtxtStarosta.setText("Королев П. Р.");
        jtxtCourseTeacher.setText("Орлов К. Б.");
        }
        else if (jcboCourse.getSelectedItem().equals("Правоохранительная деятельность"))
    {
        jtxtCourseCode.setText("PD0001");
        jtxtFaculty.setText("ИПСУБ");
        jtxtDekan.setText("к-т юр. наук Ившин В. Г");
        jtxtStarosta.setText("Титов А. А.");
        jtxtCourseTeacher.setText("Родионов М. С.");
        }
        else if (jcboCourse.getSelectedItem().equals("Информационная безопасность"))
    {
        jtxtCourseCode.setText("IS0001");
        jtxtFaculty.setText("ИПСУБ");
        jtxtDekan.setText("к-т юр. наук Ившин В. Г");
        jtxtStarosta.setText("Смирнов Е. Л.");
        jtxtCourseTeacher.setText("Першин А. И.");
        }

       else if (jcboCourse.getSelectedItem().equals("Выберите предмет"))
    {
            JTextField jtxt = null;
        for (Component c:jPanel4.getComponents())
         {
             if (c.getClass().toString().contains("javax.swing.JTextField"))
             {
                 jtxt = (JTextField)c;
                 jtxt.setText(null);
             }
           }
        }
    }//GEN-LAST:event_jcboCourseActionPerformed


    private void jtxtDekanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDekanActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDekanActionPerformed

    private void jtxtCourseTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCourseTeacherActionPerformed
        // TOO add your handling code here:
    }//GEN-LAST:event_jtxtCourseTeacherActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        // TODO add your handling code here:
        try {
            jtxtTranscript.print();
        }
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("Принтер не найден", e.getMessage());
        }


    }//GEN-LAST:event_jbtnPrintActionPerformed
    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        // TODO add your handling code here:

        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Вы хотите закрыть программу?", "Система учета рейтинга студентов",
                JOptionPane.YES_NO_OPTION  ) == JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResultActionPerformed
        // TODO add your handling code here:
        int[] score = new int[9];

        score[0] = Integer.parseInt(jtxtScore1.getText());
        score[1] = Integer.parseInt(jtxtScore2.getText());
        score[2] = Integer.parseInt(jtxtScore3.getText());
        score[3] = Integer.parseInt(jtxtScore4.getText());
        score[4] = Integer.parseInt(jtxtScore5.getText());
        score[5] = Integer.parseInt(jtxtScore6.getText());
        score[6] = Integer.parseInt(jtxtScore7.getText());
        score[7] = Integer.parseInt(jtxtScore8.getText());

        score[8] = score[0] + score[1] + score[2] + score[3] + score[4] + score[5] + score[6] + score[7];
        jtxtTotalScore.setText(Integer.toString(score[8]));

        if ( score[8] >= 700)
        {
            jtxtRanking.setText("Высокая успеваемость");
        }
        else if  (score[8] >= 600)
        {
            jtxtRanking.setText("Выше среднего");
        }
        else if  (score[8] >= 500)
        {
            jtxtRanking.setText("Хорошая успеваемость");
        }
        else if  (score[8] >= 400)
        {
            jtxtRanking.setText("Достаточная успеваемость");
        }
        else if  (score[8] >= 300)
        {
            jtxtRanking.setText("Удовлетворительно");
        }
        else if  (score[8] <= 299)
        {
            jtxtRanking.setText("Неудовлетворительно");
        }

        Calendar ToDay = Calendar.getInstance();
        ToDay.getTime();
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyyy");
        jtxtDate.setText(Tdate.format(ToDay.getTime()));

        if  (score[0] > 100)
        {
            jtxtScore1.setText("0");
        }

        if  (score[1] > 100)
        {
            jtxtScore2.setText("0");
        }

        if  (score[2] > 100)
        {
            jtxtScore3.setText("0");
        }

        if  (score[3] > 100)
        {
            jtxtScore4.setText("0");
        }

        if  (score[4] > 100)
        {
            jtxtScore5.setText("0");
        }

        if  (score[5] > 100)
        {
            jtxtScore6.setText("0");
        }

        if  (score[6] > 100)
        {
            jtxtScore7.setText("0");
        }

        if  (score[7] > 100)
        {
            jtxtScore8.setText("0");
        }
    }//GEN-LAST:event_jbtnResultActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
         // TODO add your handling code here:
         JTextField jtxt = null;
         JComboBox jcbo = null;



         for (Component c:jPanel7.getComponents())
         {
             if (c.getClass().toString().contains("javax.swing.JTextField"))
             {
                 jtxt = (JTextField)c;
                 jtxt.setText(null);
             }
         }

         for (Component c:jPanel5.getComponents())
         {
             if (c.getClass().toString().contains("javax.swing.JComboBox"))
             {
                 jcbo = (JComboBox)c;
                 jcbo.setSelectedIndex(0);
             }
         }
         for (Component c:jPanel5.getComponents())
         {
             if (c.getClass().toString().contains("javax.swing.JTextField"))
             {
                 jtxt = (JTextField)c;
                 jtxt.setText(null);
             }
         }

         for (Component c:jPanel4.getComponents())
         {
             if (c.getClass().toString().contains("javax.swing.JTextField"))
             {
                 jtxt = (JTextField)c;
                 jtxt.setText(null);
             }
         }
         // Сделаем раздельно для выбора пола, расшифровки  и предмета
    jtxtTranscript.setText(null);
    jcboGender.setSelectedIndex(0);
    jcboCourse.setSelectedIndex(0);





    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        // all of the rules for the fields
        try 
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlCon = DriverManager.getConnection(dataCon, username, password);
            pst = sqlCon.prepareStatement("insert into resultdb(StudentID, Firstname, Surname, Otchestvo, Gender," 
                + "DOB, Mobile, Email, Course, CourseCode," +
                "Module1, Module2, Module3, Module4, Module5, Module6, Module7, Module8," +
                "Score1, Score2, Score3, Score4, Score5, Score6, Score7, Score8, TotalScore, Ranking, Date)"
                    + "value(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
        
        pst.setString(1, (String)jtxtStudentID.getText());
        pst.setString(2, (String)jtxtFirstname.getText());
        pst.setString(3, (String)jtxtSurname.getText());
        pst.setString(4, (String)jtxtOtchestvo.getText());
        pst.setString(5, (String) jcboGender.getSelectedItem());
        pst.setString(6, jtxtDOB.getText());
        pst.setString(7, jtxtMobile.getText());
        pst.setString(8, jtxtEmail.getText());
        
        pst.setString(9, (String)jcboCourse.getSelectedItem());
        pst.setString(10, jtxtCourseCode.getText());
        
        pst.setString(11, (String)jcboModule1.getSelectedItem());
        pst.setString(12,(String) jcboModule2.getSelectedItem());
        pst.setString(13, (String)jcboModule3.getSelectedItem());
        pst.setString(14, (String)jcboModule4.getSelectedItem());
        pst.setString(15, (String)jcboModule5.getSelectedItem());
        pst.setString(16, (String)jcboModule6.getSelectedItem());
        pst.setString(17, (String)jcboModule7.getSelectedItem());
        pst.setString(18, (String)jcboModule8.getSelectedItem());
        
        pst.setString(19, (String)jtxtScore1.getText());
        pst.setString(20, (String)jtxtScore2.getText());
        pst.setString(21, (String)jtxtScore3.getText());
        pst.setString(22, (String)jtxtScore4.getText());
        pst.setString(23, (String)jtxtScore5.getText());
        pst.setString(24, (String)jtxtScore6.getText());
        pst.setString(25, (String)jtxtScore7.getText());
        pst.setString(26, (String)jtxtScore8.getText());
        
        pst.setString(27, (String)jtxtTotalScore.getText());
        pst.setString(28, (String)jtxtRanking.getText());
        pst.setString(29, (String)jtxtDate.getText());
        
       pst.executeUpdate();
       JOptionPane.showMessageDialog(this, "Результаты студента обновлены");
       uploadDB();
        
        }
        catch(ClassNotFoundException | SQLException ex)
        {
            java.util.logging.Logger.getLogger(FacultyOfLawStudentResultSystem.class.getName()).log
                (java.util.logging.Level.SEVERE,null, ex);
        }
        
        
    }//GEN-LAST:event_jbtnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacultyOfLawStudentResultSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacultyOfLawStudentResultSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacultyOfLawStudentResultSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacultyOfLawStudentResultSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacultyOfLawStudentResultSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnResult;
    private javax.swing.JButton jbtnTranscript;
    private javax.swing.JComboBox<String> jcboCourse;
    private javax.swing.JComboBox<String> jcboGender;
    private javax.swing.JComboBox<String> jcboModule1;
    private javax.swing.JComboBox<String> jcboModule2;
    private javax.swing.JComboBox<String> jcboModule3;
    private javax.swing.JComboBox<String> jcboModule4;
    private javax.swing.JComboBox<String> jcboModule5;
    private javax.swing.JComboBox<String> jcboModule6;
    private javax.swing.JComboBox<String> jcboModule7;
    private javax.swing.JComboBox<String> jcboModule8;
    private javax.swing.JTextField jtxtCourseCode;
    private javax.swing.JTextField jtxtCourseTeacher;
    private javax.swing.JTextField jtxtDOB;
    private javax.swing.JTextField jtxtDate;
    private javax.swing.JTextField jtxtDekan;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtFaculty;
    private javax.swing.JTextField jtxtFirstname;
    private javax.swing.JTextField jtxtMobile;
    private javax.swing.JTextField jtxtOtchestvo;
    private javax.swing.JTextField jtxtRanking;
    private javax.swing.JTextField jtxtScore1;
    private javax.swing.JTextField jtxtScore2;
    private javax.swing.JTextField jtxtScore3;
    private javax.swing.JTextField jtxtScore4;
    private javax.swing.JTextField jtxtScore5;
    private javax.swing.JTextField jtxtScore6;
    private javax.swing.JTextField jtxtScore7;
    private javax.swing.JTextField jtxtScore8;
    private javax.swing.JTextField jtxtStarosta;
    private javax.swing.JTextField jtxtStudentID;
    private javax.swing.JTextField jtxtSurname;
    private javax.swing.JTextField jtxtTotalScore;
    private javax.swing.JTextField jtxtTotalScore1;
    private javax.swing.JTextField jtxtTotalScore2;
    private javax.swing.JTextArea jtxtTranscript;
    // End of variables declaration//GEN-END:variables
}
